# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('cr_date', models.DateField(auto_now=True)),
                ('notice_details', models.FileField(blank=True, null=True, upload_to='doc\\')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('name_pet', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('breed', models.CharField(max_length=200, null=True)),
                ('age_pet', models.IntegerField(default=1)),
                ('myimg', models.ImageField(null=True, upload_to='images\\', validators=[gallery.models.validate_img])),
                ('myimg_pet', models.ImageField(null=True, upload_to='images\\', validators=[gallery.models.validate_img])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
